### PR TITLE
Support injecting html inside html('') 

### PR DESCRIPTION
**Pull request by koxudaxi**
This PR adds a feature that injects HTML inside `html('')`
`html()` is as follows.

1. [viewdom.html](https://github.com/pauleveritt/viewdom)

```python
from viewdom import html

html('<div>Hello World</div>')
```

2. decorated  with [htm.htm](https://github.com/jviide/htm.py)
```python
@htm
def custom_html(tag, props, children):
    return tag, props, children


custom_html('<div>Hello World</div>')
```

## ScreenShots

Screenshot_2020-08-29_03-01-11
Screenshot_2020-08-29_03-23-37

### CODE REVIEW

**Comment by pauleveritt** [comment]
I have IntelliJ Ultimate nightly build. I got some warnings during the build. Would it be better for our discussions if I switch to 2020.2.x ?

```
> Task :buildSearchableOptions
Download https://cache-redirector.jetbrains.com/jetbrains.bintray.com/intellij-jbr/jbr-11_0_7-osx-x64-b944.20.tar.gz
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.intellij.util.ReflectionUtil to field java.awt.event.InvocationEvent.runnable
WARNING: Please consider reporting this to the maintainers of com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2020-08-29 09:03:48,906 [    956]   WARN - llij.ide.plugins.PluginManager - Resource bundle redefinition for plugin 'com.jetbrains.pycharm.community.customization'. Old value: messages.ActionsBundle, new value: messages.PyBundle 
2020-08-29 09:03:50,041 [   2091]   WARN - j.internal.DebugAttachDetector - Unable to start DebugAttachDetector, please add `--add-exports java.base/jdk.internal.vm=ALL-UNNAMED` to VM options 
Starting searchable options index builder
2020-08-29 09:03:50,673 [   2723]   WARN - nSystem.impl.ActionManagerImpl - keymap "Visual Studio" not found [Plugin: com.intellij] 
2020-08-29 09:03:50,675 [   2725]   WARN - nSystem.impl.ActionManagerImpl - keymap "Eclipse" not found [Plugin: com.intellij] 
2020-08-29 09:03:50,675 [   2725]   WARN - nSystem.impl.ActionManagerImpl - keymap "NetBeans 6.5" not found [Plugin: com.intellij] 
2020-08-29 09:03:50,675 [   2725]   WARN - nSystem.impl.ActionManagerImpl - keymap "Visual Studio" not found [Plugin: com.intellij] 
2020-08-29 09:03:50,680 [   2730]   WARN - nSystem.impl.ActionManagerImpl - keymap "Eclipse (Mac OS X)" not found [Plugin: com.intellij] 
2020-08-29 09:03:50,680 [   2730]   WARN - nSystem.impl.ActionManagerImpl - keymap "Xcode" not found [Plugin: com.intellij] 
2020-08-29 09:03:50,709 [   2759]   WARN - nSystem.impl.ActionManagerImpl - keymap "Eclipse" not found [Plugin: PythonCore] 
2020-08-29 09:03:50,709 [   2759]   WARN - nSystem.impl.ActionManagerImpl - keymap "NetBeans 6.5" not found [Plugin: PythonCore] 
Searchable options index builder completed

> Task :jarSearchableOptions
> Task :buildPlugin
> Task :assemble
> Task :compileTestKotlin NO-SOURCE
> Task :compileTestJava NO-SOURCE
> Task :processTestResources NO-SOURCE
> Task :testClasses UP-TO-DATE
> Task :instrumentTestCode NO-SOURCE
> Task :postInstrumentTestCode
> Task :prepareTestingSandbox
> Task :test NO-SOURCE
> Task :check UP-TO-DATE
> Task :build

BUILD SUCCESSFUL in 35s
13 actionable tasks: 13 executed
9:04:00 AM: Task execution finished 'build'.
```

**Comment by pauleveritt** [comment]
I also have PyCharm nightly build. The plugin says it is incompatible so I will switch to release versions.

**Comment by pauleveritt** [comment]
Ok, plugin installed. For the preferences, I expected a preferences search for `htmpy` to land on Editor -> Language Injections. But I've never gone to the Language Injections preferences before. Perhaps items in there aren't searchable.

**Comment by pauleveritt** [comment]
It works! Very nice to see. I tried a couple of things to break it and it worked fine. I will continue trying during the next hour, then we will merge, close this milestone, do the first payment.

**Comment by koxudaxi** [comment]
> I have IntelliJ Ultimate nightly build. I got some warnings during the build. Would it be better for our discussions if I switch to 2020.2.x ?

Sorry, I don't know why the Gradle script shows the warnings. But, I guess the errors may related build configs.

> I also have PyCharm nightly build. The plugin says it is incompatible so I will switch to release versions.

The problem may depend on these lines 
https://github.com/pauleveritt/htmpy-pycharm-plugin/blob/1ef96b3b501c6f6aa263d2c46affa6bb7cd5ee69/build.gradle#L29-L32

>  I expected a preferences search for htmpy to land on Editor -> Language Injections. But I've never gone to the Language Injections preferences before. Perhaps items in there aren't 
searchable.

I met this problem in my environment too. I could resolve the problem after restart PyCharm.

I push only the minimum code. If you need anything, then please write documents or change code.

**Pull request merged**
