### PR TITLE
Support tagged htm parser

### PR DESCRIPTION
**Pull request by koxudaxi**
This PR supports resolving the referenced python object in tagged HTML.

### CODE REVIEW

**Comment by pauleveritt** [comment]
I built/installed the plugin. It still says 0.0.1 with no mention in the release notes, so I hope I built and installed the correct thing. I did an uninstall first, restarted, then an install.

But no luck. I will email a small video.

**Comment by pauleveritt** [comment]
Hmm, I'm wrong, it is working now. I will continue to evaluate.

**Comment by pauleveritt** [comment]
Got several of these:

```
java.lang.IllegalArgumentException: Invalid range specified: (0, -1); 
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:221)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:216)
	at com.intellij.openapi.util.TextRange.assertProperRange(TextRange.java:212)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:40)
	at com.intellij.openapi.util.TextRange.<init>(TextRange.java:29)
	at com.koxudaxi.htmpy.HtmpyInjector$Companion.registerPyElementInjection(HtmpyInjector.kt:52)
	at com.koxudaxi.htmpy.HtmpyInjector$Companion.access$registerPyElementInjection(HtmpyInjector.kt:31)
	at com.koxudaxi.htmpy.HtmpyInjector.registerInjection(HtmpyInjector.kt:22)
	at com.jetbrains.python.codeInsight.PyInjectorBase.getLanguagesToInject(PyInjectorBase.java:33)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.processInPlaceInjectorsFor(InjectedLanguageManagerImpl.java:411)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.probeElementsUp(InjectedLanguageUtil.java:345)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageUtil.enumerate(InjectedLanguageUtil.java:164)
	at com.intellij.psi.impl.source.tree.injected.InjectedLanguageManagerImpl.enumerateEx(InjectedLanguageManagerImpl.java:311)
	at com.intellij.codeInsight.daemon.impl.InjectedGeneralHighlightingPass.lambda$getInjectedPsiFiles$3(InjectedGeneralHighlightingPass.java:189)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:149)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:162)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:162)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:162)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.jetbrains.rdserver.BackendProgressManager.executeProcessUnderProgress(BackendProgressManager.kt:75)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:117)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by pauleveritt** [comment]
I believe that exception is related to this:

```python
html('')
```

**Comment by koxudaxi** [comment]
@pauleveritt 
Thank you for testing it.

> I believe that exception is related to this:

I have fixed the problem.
The plugin parses code only when it detects `{}`.

https://github.com/pauleveritt/htmpy-pycharm-plugin/blob/17a9bab50345fe2b460e75b4dfd9295371c9125a/src/com/koxudaxi/htmpy/HtmpyInjector.kt#L50-L56

**Pull request merged**
